### ISSUE TITLE
Use Angular-Storage to keep track of logged-in users

### ISSUE THREAD

**Issue by khooweihiong** [StarTrackDevKL/announcement-board#35]
Related to #11

**Comment by khooweihiong** [comment]
bower install a0-angular-storage

**Comment by khooweihiong** [comment]
I found out that user's data such as username, token is saved into mongodb. In this case, angular-storage might not be needed.

**Comment by rashidi** [comment]
We're saving it in database for REST purpose. The server will authenticate the user against the token. Angular is needed in order to communicate with REST.

Remember that Angular is unaware of the database. It's a dumb front end.

**Comment by khooweihiong** [comment]
ok
