### ISSUE TITLE
Add Http Interceptor for Request and Response Error

### ISSUE THREAD

**Issue by khooweihiong** [StarTrackDevKL/announcement-board#38]
Related to #11

**Comment by rashidi** [comment]
Are you certain that the interceptor is working?

**Comment by khooweihiong** [comment]
i test and it did intercept the every request...but i have yet to test that the access token is retrieved to added to the header

**Comment by rashidi** [comment]
Sorry. I believe my question was unclear. I'm sure it intercepts. But does it pass the correct value to server?

**Comment by khooweihiong** [comment]
The value i append to the header, i assume, is token value, which is found in the authorization collection, am i right?

**Comment by rashidi** [comment]
It breaks when I changed 

`var currentAuthorization = null;//Authorization.getCurrentAuthorization();`

to

`var currentAuthorization = Authorization.getCurrentAuthorization();`

**Comment by khooweihiong** [comment]
That's not latest code
