### ISSUE TITLE
Page Failed to Load

### ISSUE THREAD

**Issue by rashidi** [StarTrackDevKL/announcement-board#41]
Index page failed to load due to missing `angular-storage`.

**Comment by khooweihiong** [comment]
Sorry for any inconvenience, i think i will remove angular-storage for the moment.

**Comment by rashidi** [comment]
Remove it? Why?

**Comment by khooweihiong** [comment]
I do not use it so far...unless you use it then i keep

**Comment by rashidi** [comment]
How did you store the user information for future REST calls?

**Comment by khooweihiong** [comment]
mongodb

**Comment by khooweihiong** [comment]
Way back in angular-storage
