### ISSUE TITLE
Write user stories

### ISSUE THREAD

**Issue by rasyadi** [StarTrackDevKL/announcement-board#8]
This project should have user stories as requirements to drive the development. I suggest we use wiki as a single source of truth for the user stories. We can create issues with 'user story' label and link it to the wiki page for each of the user stories.

A user story typically follows a simple template:

As a *type of user*, 
I want *to perform some task*
so that I can *achieve some goal/benefit/value*. 

User stories need to be confirmed with the 3C guidelines below, suggested by Ron Jeffries:

**Card:** User stories are traditionally written on index cards or sticky notes, in short form. User narratives further explain these cards. Thus the main intention is to describe the user story in short form to allow common understanding of the user need among all stakeholders.

**Conversation:** User stories shift the focus from writing about features to discussing them. In fact, these discussions are more important than whatever text is written.

**Confirmation:** Acceptance tests confirm that the story was delivered correctly.
Let us take an example.

**User story title:** Customer withdraws cash.

**_As a_** customer,
**_I want to_** withdraw cash from an ATM
**_So that_** I don't have to wait in line at the bank.

**Acceptance Criterion 1:**

**_Given_** that the account is creditworthy
   And the card is valid
   And the dispenser contains cash,
**_When_** the customer requests the cash
**_Then_** ensure the account is debited
   And ensure cash is dispensed
   And ensure the card is returned.

**Acceptance Criterion 2:**

**_Given_** that the account is overdrawn
   And the card is valid,
**_When_** the customer requests the cash
**_Then_** ensure the rejection message is displayed
   And ensure cash is not dispensed.

- See more at: https://www.scrumalliance.org/community/articles/2013/september/agile-user-stories#sthash.vPvXdgBe.dpuf

**Comment by rashidi** [comment]
We actually do have a label user story to mark a request as a user story. I'd prefer the wiki being used to explain about the feature of the system in form of user manual rather than user story.

**Comment by rasyadi** [comment]
No big deal. We can just use issues for the user stories and leave wiki as is for now.
